name: Build IPK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build ipk
        run: |
          chmod +x build-ipk.sh
          sed -i 's/\r$//' build-ipk.sh
          sh build-ipk.sh

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: luci-app-socksbind-ipk
          path: "*.ipk"

      - name: Publish Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v1.0.0
          files: "*.ipk"
